name: robustxai
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - captum=0.5.0
  - h5py=3.7.0
  - imbalanced-learn=0.9.1
  - joblib=1.2.0=pyhd8ed1ab_0
  - matplotlib-base=3.5.3
  - networkx=2.8.4
  - numpy=1.23.4
  - pandas=1.5.1
  - pip=22.2.2
  - pyg=2.2.0
  - python=3.10.8
  - pytorch=1.13.0
  - scikit-learn=1.1.3
  - seaborn=0.12.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tqdm=4.64.1
  - pip:
    - build==0.10.0
    - docopt==0.6.2
    - kaggle==1.5.12
    - pip-tools==6.12.3
    - pipreqs==0.4.11
    - pyproject-hooks==1.0.0
    - python-slugify==7.0.0
    - text-unidecode==1.3
    - yarg==0.1.9
    - pytorch-lightning==2.0.2
    - e2cnn==0.2.3
    - wandb==0.15.0

